CREATE DATABASE WEATHER_METRICS;

USE WEATHER_METRICS;

CREATE TABLE SENSOR(SENSOR_ID INT NOT NULL, COUNTRY_NAME CHAR(50), CITY_NAME CHAR(50), PRIMARY KEY(SENSOR_ID));

CREATE TABLE METRICS(METRIC_ID INT NOT NULL AUTO_INCREMENT, SENSOR_ID INT NOT NULL, DATE DATETIME, TEMPERATURE FLOAT, PRECIPITATION FLOAT, WIND_SPEED FLOAT, 
PRIMARY KEY(METRIC_ID),
FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(SENSOR_ID));

